#spring.application.name=REST-API-Demo
#spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
#spring.datasource.username=springstudent
#spring.datasource.password=springstudent
#
#
#spring.data.rest.base-path=/api/v1
#spring.security.user.name=sc
#spring.security.user.password=123


# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=system
spring.datasource.password=toor

# JDBC Driver for Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA Hibernate Dialect for Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Hibernate settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

